### ISSUE TITLE
[BUG] Custom variable

### ISSUE THREAD

**Issue by EspadaCZ** [CraftingStore/Suggestions#132]
Hello, I have found problem with custom variable.

**Describe the bug**
Custom variable is not changed to value in "Expiry command" and is send in {variable} format to server.
In "Initial command" everything works.

**Example**
Initial command:
     Package settings: "give {player} {uid} vip"
     Server recieves: "give EspadaCZ 1 vip"
Expiry command:
     Package settings: "take {player} {uid} vip"
     Server recieves: "take EspadaCZ {uid} vip"

**Expected behavior**
I Expect that custom variable is changed to value in Expiry command.

**Platform**
CraftingStore website

**Comment by Tim-NL** [comment]
Hi,

This issue was resolved some time ago, but we never updated this issue, sorry about that. 

-Tim

**Comment by EspadaCZ** [comment]
Hello, I have tried it today again and looks like it is still broken. The exactly same problem as before. I have tried to re-add the custom variable which did not help.

**Comment by Tim-NL** [comment]
Hi,

The issue is now resolved. Placeholders will now show up correctly in expiry commands. 

Thanks for trying it out the second time!

-Tim
