### ISSUE TITLE
Categories bug in plugin.

### ISSUE THREAD

**Issue by Tim-NL** [CraftingStore/Suggestions#22]
Feature Request 1
General Feature Title: Ingame /buy - Subcategories are IN their PARENT categories.

Issue: I had to rename all of my subcategories because when you do /buy in-game - It will not put Ranks or Perks in their parent category.

Outcome: All subcategories should be IN their parent category in /buy

Issue 1 - Related to Feature Request 1
General Feature Title: Subcategories with the same name will only show one of the actual items in the subcategory. The other one just doesn't show.

Outcome: I wish for this to be fixed. So I can just name my Survival and Skyblock subcategories to just

Perks

and not have to call it

Survival Perks or Skyblock Perks

Its kind of an inconvenience and un-needed!

--
Copy of @Exophobias's issue (#21) to separate them.

**Comment by Tim-NL** [comment]
We've pushed a plugin update to Spigot & our CDN servers to fix this issue.

Link: https://www.spigotmc.org/resources/craftingstore-net-free-minecraft-donation-system-1-13-compatible.31331/

~Tim

**Comment by Exophobias** [comment]
@Tim-NL You didn't fix it. 

It no longer shows sub-categories in the main /buy menu BUT when you click on Survival, it doesn't have any items in it because all the packages are in sub-categories.

So you kinda fixed it by removing them from the main page but it doesn't go into its parent category.
Also, the main parent categories aren't even in proper order either.

On my store admin page it goes - Minigames, Survival, Skyblock, Creative

Ingame (/buy) it goes Minigames, Skyblock, Creative, Survival

**Comment by Tim-NL** [comment]
The GUI for the plugin is not finnished, and was released as a test, there is no support for sub categories just yet. And the order is incremental (based on ID), I'll look into both issues that. 

~Tim
