### ISSUE TITLE
someone bought a rank but craftingstore didnt send the commands

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#279]
**Describe the bug**
someone bought a rank but craftingstore didnt send the commands

**To Reproduce**
i don't know how to reproduce it. I tried with manual payment but still not working.

**Expected behavior**
The commands are not appear when someone buy something

**Screenshots**
https://imgur.com/a/ui96Y1x

**Platform**
CraftingStore

**Additional context**
-

**Comment by Tim-NL** [comment]
Sorry, missed this issue. This has been resolved months ago already.

-Tim

**Comment by TerrorGamesOff** [comment]
Hello! The issue it's not fixed, it happens on 29.04.2020

În mar., 5 mai 2020 la 20:35, Tim Kwakman <notifications@github.com> a
scris:

**Comment by Tim-NL** [comment]
The store not loading the commands was resolved a few months ago and only happened for a short period. 

If the server does not execute the commands (but they do show up on the dashboard as "queued") its another issue, most likely between the CraftingStore API and Game server. 

Those issues must be looked in on a server-by-server basis and is not related to the issue in the screenshot here.

-Tim

**Comment by TerrorGamesOff** [comment]
Ohhh sorry my bad, i tought that was other bug report.
Sorry!

În mar., 5 mai 2020 la 20:43, Tim Kwakman <notifications@github.com> a
scris:

**Comment by TerrorGamesOff** [comment]
Yes, this problem was fixed.
